### ISSUE TITLE
Manipulation matrix large than 4x4 ?

### ISSUE THREAD

**Issue by perlawk** [devurandom/lua-eigen#1]
How do I input a matrix more than 4x4 size?
There are only examples for 4x4 size, but not 5x5 or more?
How to access the individual elements of a matrix?
Thank you!

**Comment by devurandom** [comment]
For larger sizes there are only dynamic matrices (since for static ones the size has to be known at compiletime, and I cannot preemptively create all kinds of matrices, but the most common ones).

``` lua
local m = eigen.MatrixXf(…) -- initialise
m(row, col, f) -- set value
f = m(row, col) -- read value
```

When initialising a dynamic matrix, you have to use "raw" arguments — not a table. Initialisiation using tables (of numbers or vectors) is available only for static matrices.

See [src/matrix.hpp](https://github.com/devurandom/lua-eigen/blob/master/src/matrix.hpp) for the available methods.
